create database locadora;
use locadora;

create table categorias (
	id int primary key auto_increment,
    nome varchar(50) not null,
    publico_alvo varchar(50)
);

create table filmes (
	id int primary key auto_increment,
    titulo varchar(200) not null,
    sinopse varchar(5000),
    estudio varchar(80),
    categoria_id int,
    constraint fk_categorias foreign key(categoria_id) references categorias(id)
);

insert into categorias (nome, publico_alvo)
values ('Ação', 'Adultos e adolescentes'), ('Animação', 'Crianças e famílias'), ('Terror', 'Adultos');

insert into filmes ( titulo, sinopse, estudio, categoria_id)
values ('Fale Comigo', 'No terror Fale Comigo, da A24, conjurar espíritos tornou-se a última moda nas festas locais e, procurando uma distração no aniversário de morte da mãe, Mia está determinada a participar da trend. Na trama, acompanhamos o grupo de amigos que encontra uma misteriosa mão embalsamada e descobre que ela permite invocar espíritos. Como é de se esperar, todos ficam muito empolgados com a nova descoberta, mas não demora muito até que a brincadeira tome um rumo extremamente perigoso quando um deles acaba indo longe demais e, por acidente, abre uma porta para o mundo espiritual. Agora, com todos altamente vulneráveis a várias ameaças aterrorizantes, cada um dos amigos será obrigado a lidar com uma difícil escolha, descobrindo em quem devem confiar: nos mortos da outra dimensão ou nos vivos. Protagonizado por Sophie Wilde, Miranda Otto, Alexandra Jensen, Joe Bird, Otis Djanji e Zoe Terakes, o filme é dirigido pela dupla de estreantes em longas-metragens, Danny e Michael Philippou.', 'A24', 3),
('John Wick 1', 'John Wick (Keanu Reeves) já foi um dos assassinos mais temidos da cidade de Nova York, trabalhando em parceria com a máfia russa. Um dia, ele decide se aposentar, e neste período tem que lidar com a triste morte de sua esposa. Vítima de uma doença grave, ela já previa a sua própria morte, e deu de presente ao marido um cachorro para cuidar em seu período de luto. No entanto, poucos dias após o funeral, o cachorro é morto por ladrões que roubam o seu carro. John Wick parte em busca de vingança contra estes homens que ele já conhecia muito bem, e que roubaram o último símbolo da mulher que ele amava.', 'Lionsgate', 1),
('John Wick 2', 'Após recuperar seu carro, John Wick (Keanu Reeves) acredita que enfim poderá se aposentar. Entretanto, a reaparição de Santino DAntonio (Riccardo Scarmacio) atrapalha seus planos. Dono de uma promissória em nome de Wick, por ele usada para deixar o posto de assassino profissional da Alta Cúpula, Santino cobra a dívida existente e insiste para que ele mate sua própria irmã, Gianna (Claudia Gerini).', 'Lionsgate', 1),
('John Wick 3', 'Após assassinar o chefe da máfia Santino DAntonio (Riccardo Scamarcio) no Hotel Continental, John Wick (Keanu Reeves) passa a ser perseguido pelos membros da Alta Cúpula sob a recompensa de U$14 milhões. Agora, ele precisa unir forças com antigos parceiros que o ajudaram no passado enquanto luta por sua sobrevivência.', 'Lionsgate', 1),
('John Wick 4', 'O assassino profissional retorna às telas para John Wick 4: Baba Yaga. O assassino profissional John Wick (Keanu Reeves) agora virou metade do submundo contra ele com sua vingança, que agora está entrando em sua quarta rodada em Nova York, Berlim, Paris e Osaka. Sua equipe, composta por Bowery King (Laurence Fishburne), o gerente do hotel Winston (Ian McShane) e o concierge Charon (Lance Reddick) do lendário hotel assassino Continental, novamente fazem parte da festa. No entanto, as chances de escapar desta vez parecem quase impossíveis, pois o maior inimigo está surgindo. O implacável chefe do submundo Marquis de Gramont (Bill Skarsgård), que tem alianças inteiras atrás dele, representa a maior e sanguinária ameaça até hoje. Mas seus capangas também são durões, incluindo Shimazu (Hiroyuki Sanada) e Killa (Scott Adkins) localizados. Felizmente, existem velhos aliados como Caine (Donnie Yen) que correm para ajudar Wick. Não há caminho de volta, só um sobrevive.', 'Lionsgate', 1),
('Elementos', 'Elementos é um filme de animação que se passa em uma sociedade extraordinária chamada Cidade Elemento, na qual os quatro elementos da natureza - ar, terra, fogo e ar - vivem em completa harmonia. Na história, somos apresentados à Faísca (fogo, dublada por Leah Lewis), uma mulher espirituosa na faixa dos vinte anos, com um grande senso de humor e apaixonada pela família, mas que tem um temperamento um pouco quente; Gota (água, dublado por Mamoudou Athie) é um jovem empático, observador e extrovertido, que não tem medo de demonstrar suas emoções - na verdade, é até um pouco difícil controlá-las; Turrão (terra, dublado por Mason Wertheimer) é um garoto muito inteligente da terra que mora na Vila do Fogo, e está sempre perto de Faísca; e Névoa (ar, dublada por Wendi McLendon-Covey), que tem uma personalidade fofa e rosa, está sempre atenta às tendências da moda e é fã dos Windbreakers, um time de Air Ball.', 'Disney', 2),
('Divertida Mente', 'Riley é uma garota divertida de 11 anos de idade, que deve enfrentar mudanças importantes em sua vida quando seus pais decidem deixar a sua cidade natal, no estado de Minnesota, para viver em San Francisco. Dentro do cérebro de Riley, convivem várias emoções diferentes, como a Alegria, o Medo, a Raiva, o Nojinho e a Tristeza. A líder deles é Alegria, que se esforça bastante para fazer com que a vida de Riley seja sempre feliz. Entretanto, uma confusão na sala de controle faz com que ela e Tristeza sejam expelidas para fora do local. Agora, elas precisam percorrer as várias ilhas existentes nos pensamentos de Riley para que possam retornar à sala de controle - e, enquanto isto não acontece, a vida da garota muda radicalmente.', 'Disney', 2),
('Hereditário', 'Quando sua mãe - que sofria de distúrbios mentais - falece, Annie (Toni Collette), seu marido (Gabriel Byrne), filho (Alex Wolff) e filha (Milly Shapiro) lamentam sua perda. Todavia, após a morte da reclusa avó, a família Graham começa a desvendar algumas coisas. A família recorre a diferentes meios para lidar com sua dor, incluindo Annie e sua filha flertando com o sobrenatural. Mesmo após a partida da matriarca, ela permanece como se fosse um sombra sobre a família, especialmente sobre a solitária neta adolescente, Charlie, por quem ela sempre manteve uma fascinação não usual. Com um crescente terror tomando conta da casa, a família explora lugares mais obscuros para escapar do infeliz destino que herdaram. Cada um deles começa a ter experiências perturbadoras e sobrenaturais ligadas aos segredos sinistros e traumas emocionais que passaram pelas gerações de sua família.', 'A24', 3);

select * from filmes f join categorias c on c.id = f.categoria_id;